services:
  api:
    container_name: gerenciabook
    image: node:20
    working_dir: /usr/src/gerenciabook
    restart: always
    environment:
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_HOST=my-postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=GerenciaBook
    volumes:
      - ./dist:/usr/src/gerenciabook/dist
      - ./package.json:/usr/src/gerenciabook/package.json
      - ./package-lock.json:/usr/src/gerenciabook/package-lock.json
    ports:
      - "3000:3000"
      - "9222:9222"
    command: bash -c "npm install --only=prod --force && npm run dev -- --exitcrash"
    networks:
      - my-network
networks:
  my-network:
    name: my-network
    external: true