services:
  api:
    container_name: gerenciabook
    image: node:20
    working_dir: /usr/src/gerenciabook
    restart: always
    volumes:
      - ./dist:/usr/src/gerenciabook/dist
      - ./package.json:/usr/src/gerenciabook/package.json
      - ./package-lock.json:/usr/src/gerenciabook/package-lock.json
    ports:
      - "3000:3000"
      - "9222:9222"
    command: bash -c "npm install --only=prod --force && npm run debug"
    